name: Code Check

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint, format and check types
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup // [!code highlight]
        uses: actions/cache@v4 // [!code highlight]
        with: 
          path: .turbo // [!code highlight]
          key: ${{ runner.os }}-turbo-${{ github.sha }} // [!code highlight]
          restore-keys: |
            ${{ runner.os }}-turbo- // [!code highlight]

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint, format and type checks
        run: pnpm code-check
